### ISSUE TITLE
Unroll can't interpolate regex strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#115]
```
import spock.lang.*

class TheSpec extends Specification {
  @Unroll("#t")
  def t() {
    expect:
    true
    where:
    t << ["(\$|\\s)"]
  }
}
​
Yields…

java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Unknown Source)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
```

Original issue reported on code.google.com by `lda...@gmail.com` on 28 Jul 2010 at 1:25

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 28 Jul 2010 at 5:44
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 29 Jul 2010 at 11:30
- Added labels: **Milestone-0.5**

**Comment by GoogleCodeExporter** [comment]
```
Issue 122 has been merged into this issue.
```

Original comment by `pnied...@gmail.com` on 19 Aug 2010 at 2:30
