### ISSUE TITLE
@Unroll chokes when there are $$ in datatable values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#122]
```
What steps will reproduce the problem? If possible, provide source code and
stack trace

 @Unroll( "validating #email" )
  def "checmail syntax"() {

      expect:
        true

      where:
        email                               | valid
        'sj34£kls@4d@$$ddds0.com'           | false
  }

causes


Illegal group reference
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:713)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
    at grails.plugin.spock.test.GrailsSpecTestType.doRun(GrailsSpecTestType.groovy:62)
    at org.codehaus.groovy.grails.test.support.GrailsTestTypeSupport.run(GrailsTestTypeSupport.groovy:120)

in intellij idea 9

What version of Spock and Groovy are you using?
Spock 0.4-SNAPSHOT-grooovy-1.7

Please provide any additional information below. You can also assign
labels.

```

Original issue reported on code.google.com by `tomas...@gmail.com` on 19 Aug 2010 at 12:52
- Merged into: #115

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 19 Aug 2010 at 2:30
- Changed state: **Duplicate**
- Added labels: **Milestone-0.5**
