### ISSUE TITLE
Error in setupSpeck() causes NPE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#13]
```
java.lang.NullPointerException
    at
org.spockframework.runtime.JUnitSupervisor.getFeatureDescription(JUnitSupervisor
.java:90)
    at org.spockframework.runtime.JUnitSupervisor.error(JUnitSupervisor.java:61)
    at
org.spockframework.runtime.SpeckInfoBaseRunner.invokeRaw(SpeckInfoBaseRunner.jav
a:181)
    at
org.spockframework.runtime.SpeckInfoBaseRunner.invoke(SpeckInfoBaseRunner.java:1
61)
    at
org.spockframework.runtime.SpeckInfoBaseRunner.invokeSetupSpeck(SpeckInfoBaseRun
ner.java:98)
    at
org.spockframework.runtime.SpeckInfoBaseRunner.run(SpeckInfoBaseRunner.java:78)
    at spock.lang.Sputnik.run(Sputnik.java:47)
    at com.intellij.rt.junit4.Junit4ClassSuite.run(Junit4ClassSuite.java:99)
    at junit.textui.TestRunner.doRun(TestRunner.java:116)
    at
com.intellij.rt.execution.junit.IdeaTestRunner.doRun(IdeaTestRunner.java:94)
    at junit.textui.TestRunner.doRun(TestRunner.java:109)
    at
com.intellij.rt.execution.junit.IdeaTestRunner.startRunnerWithArgs(IdeaTestRunne
r.java:22)
    at
com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter
.java:118)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:90)
```

Original issue reported on code.google.com by `pnied...@gmail.com` on 10 Mar 2009 at 6:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 11 Mar 2009 at 6:32
- Changed state: **Fixed**
