### ISSUE TITLE
Error when pretty-printing multi-line conditions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#131]
```
When a multi-line condition fails, chances are that ExpressionInfoBuilder fails 
to compile the condition after flattening. Example:

expect:
[1,2,3].every {
  println it
  it > 1
}

Result:

Spec expression: 1: expecting '}', found 'it' @ line 1, column 28.
   [1,2,3].every { println it it > 1 }
                              ^

1 error

    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:296)
    at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:103)
    at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:142)
    at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:113)
    at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:125)
    at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:353)
    at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:105)
    at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:72)
    at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:249)
    at org.spockframework.runtime.ExpressionInfoBuilder.build(ExpressionInfoBuilder.java:50)
    at org.spockframework.runtime.Condition.getExpression(Condition.java:65)
    at org.spockframework.runtime.JUnitSupervisor.isCausedByFailedEqualityComparison(JUnitSupervisor.java:117)
    at org.spockframework.runtime.JUnitSupervisor.error(JUnitSupervisor.java:92)
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:237)
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:217)
    at org.spockframework.runtime.BaseSpecRunner.invokeFeatureMethod(BaseSpecRunner.java:204)
    at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:182)
    at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:235)
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:217)
    at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:152)
    at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:129)
    at org.spockframework.runtime.BaseSpecRunner.doRun(BaseSpecRunner.java:96)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:235)
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:217)
    at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:73)
    at org.spockframework.runtime.Sputnik.run(Sputnik.java:57)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)


```

Original issue reported on code.google.com by `pnied...@gmail.com` on 8 Oct 2010 at 4:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 4 Oct 2012 at 6:59
- Added labels: **Milestone-1.0**

**Comment by GoogleCodeExporter** [comment]
```
I had the same problem with something like

expect:
[foo:1] == [bar:2 // comment
]

The worst part was that I didn't realize that I had started to get the parsing 
error because my assertion had just started to fail (for other, external 
reasons).  My first thought was that I had some kind of version problem with 
Spock/Groovy/Grails.  It stumped me for about a day.

This would be a much smaller issue if we could get the parsing error up front, 
even when the assertion doesn't fail.  Can't it be evaluated and validated 
anyway?  I wouldn't mind working around it, e.g., by using /* instead of // 
comments, or by defining a local variable to hold the map (so the literal is 
not in the assertion expression).

The way it is now, though, you can add a // comment to a working test, and if 
it every fails in the future, you get a very misleading error message.
```

Original comment by `jdbeu...@gmail.com` on 23 Jul 2013 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
Issue 325 has been merged into this issue.
```

Original comment by `pnied...@gmail.com` on 12 Aug 2013 at 1:41

**Comment by GoogleCodeExporter** [comment]
```
I'm looking into this issue and it seem like for 
expect:
[1,2,3].every {
  println it
  it > 1
}
test, to avoid MultipleCompilationErrorsException, workaround is to add ';' at 
the end of 'println it' line. But I do not understand why the test passes when 
I change
[1,2,3].every {...
to
[2,3].every {...

Does it mean that MultipleCompilationErrorsException occurs only when the 
condition is evaluated to false?
What would be good approach to resolving this issue? Making Condition.flatten() 
method "smarter" by appending ';' and replacing '//' with '/* */' where 
necessary? 
```

Original comment by `vasos...@gmail.com` on 26 May 2014 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
> Does it mean that MultipleCompilationErrorsException occurs only when the 
condition is evaluated to false?

Yes.

> What would be good approach to resolving this issue? Making 
Condition.flatten() method "smarter" by appending ';' and replacing '//' with 
'/* */' where necessary? 

Inserting `;` will cause problems in case of a multi-line expression. Probably 
the best solution is to get rid of flattening and enhance `ConditionRenderer` 
to render multi-line conditions.
```

Original comment by `pnied...@gmail.com` on 27 May 2014 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
Why does the condition have to be flattened in the first place? Is this the 
nature of how AntlrParserPlugin works? It expects that SourceUnit's source is a 
string with no '\n's in it. It looks like it won't able to parse CST, if the 
condition is multi-line and hasn't been flattened. I guess I'm just trying to 
understand how the condition has to be rendered so that unit.parse() succeeds. 
Do I have to become familiar with AntlrParserPlugin?
```

Original comment by `vasos...@gmail.com` on 29 May 2014 at 3:08

**Comment by GoogleCodeExporter** [comment]
```
It doesn't have to be. The original idea was that flattening allows for better 
rendering of the expression. (Try to draw the output for a multi-line 
expression with values anchored at the same column.)
```

Original comment by `pnied...@gmail.com` on 29 May 2014 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
Sorry, but I didn't understand your recommendation. It seems to me that I need 
to find a way to distinguish between two (or perhaps more than two) types of 
multi-line conditions:
1)
    expect:
    2 *
        3 ==

        6
2)
    expect:
    [1,2,3].every {
    println it
    it > 1
    }
The first one can be flattened where as the second one can not be.
new ExpressionInfoBuilder(flatten(text), TextPosition.create(1, 1), 
values).build() is called first to get the expression which is then rendered.
unit.parse() inside build() method throws 
org.codehaus.groovy.control.MultipleCompilationErrorsException 
So it seems to me that it would make sense to render the text before it is 
passed into ExpressionInfoBuilder constructor, not after. Can I then use 
ExpressionInfoValueRenderer or ExpressionInfoRenderer classes to do that or 
they are only intended for expression rendering only as their names suggests?
```

Original comment by `vasos...@gmail.com` on 29 May 2014 at 6:10

**Comment by GoogleCodeExporter** [comment]
```
I don't understand your point. Every expression *can* be flattened technically, 
but I wonder if it's worth the effort. Instead I'm leaning towards *never* 
flattening an expression and instead implementing a reasonable rendering for 
multi-line expressions. Multi-line expressions will be the exception, and users 
can always flatten them themselves if they aren't happy with the rendering. 
```

Original comment by `pnied...@gmail.com` on 29 May 2014 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
(What I meant is that every expression can be flattened by adding semicolons in 
the right places.)
```

Original comment by `pnied...@gmail.com` on 29 May 2014 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
I think we're on the same page. There needs to be a new class for rendering the 
text before it is passed into ExpressionInfoBuilder. But I am confused on the 
meaning of the word rendering here. You're saying that introducing semi-colons 
at line breaks would be called flattening. I thought the current implementation 
of flatten() just replaces '\n' with ' '. Besides, you would not want to add 
semicolons when expression is something like:
    expect:
    2 *
        3 ==

        6
But then how do you determine when to add semicolons and when not to?
Could you give me a hint on what the requirements for this new renderer class 
might be?
```

Original comment by `vasos...@gmail.com` on 29 May 2014 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
By "rendering" I mean drawing the diagram that shows the value for each 
subexpression. To correctly flatten any expression you'd have to parse the 
expression. As I've said before, I think it's more feasible to improve the 
renderer to support multi-line expressions (and draw them in a sensible way).
```

Original comment by `pnied...@gmail.com` on 6 Jun 2014 at 4:43

**Comment by GoogleCodeExporter** [comment]
```
Issue 367 has been merged into this issue.
```

Original comment by `pnied...@gmail.com` on 1 Jul 2014 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
Issue 378 has been merged into this issue.
```

Original comment by `pnied...@gmail.com` on 16 Oct 2014 at 3:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 1 Mar 2015 at 11:45
- Added labels: **Milestone-1.1**
- Removed labels: **Milestone-1.0**
