### ISSUE TITLE
NPE on assert object.method() : "message"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#148]
```
What steps will reproduce the problem? If possible, provide source code and
stack trace.

this is failing :
assert domain.save() : "details" 
with :
java.lang.NullPointerException
    at org.spockframework.runtime.SpockRuntime.verifyMethodCondition(SpockRuntime.java:58)
    at org.spockframework.runtime.SpockRuntime$verifyMethodCondition.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)

this is working :
def a = domain.save()
assert a : "details


What version of Spock and Groovy are you using?
1.7.5 Groovy + Spock 0.5 (Grails plugin )



```

Original issue reported on code.google.com by `stephane...@gmail.com` on 26 Nov 2010 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
Peter,

I have committed a fix for this issue, but it may be covering a more insidious 
problem.

See r1240. I've merged this into the Groovy 1.7 and Groovy 1.8 branches as well.
```

Original comment by `lda...@gmail.com` on 26 Nov 2010 at 1:54

**Comment by GoogleCodeExporter** [comment]
```
Thanks Luke, looks fine to me. Problem was introduced by a recent change of 
mine.
```

Original comment by `pnied...@gmail.com` on 26 Nov 2010 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
Stephane: Please update your snapshot, and the problem should go away.
```

Original comment by `pnied...@gmail.com` on 26 Nov 2010 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
It's working ATM Peter :) We were both online whe Luke commited the fix and as 
soon I have traced the issuing line Luke added a test and a fix. Beautiful OSS 
universe :)
```

Original comment by `stephane...@gmail.com` on 26 Nov 2010 at 9:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 2 Dec 2010 at 12:18
- Changed state: **Fixed**
- Added labels: **Milestone-0.5**
