### ISSUE TITLE
where: data table with column namn "p1" does not compile

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#149]
```
What steps will reproduce the problem? If possible, provide source code and
stack trace.

// A spec with the following feature will cause compilation errors
// with the explination "null". It is related to to the name 'p1'
// changing it to p2 or foo etc works.
//
def "p1 should be a valid data table column or give a good groovy compilation 
error or at least be clearly documented"() {
        expect:
            name == "why"
            p1   == 3
        where:
            //using 'p1' will cause a groovy 1.7 compilation error "null"
            name  | p1
            "why" | 3
      }

What version of Spock and Groovy are you using?

Spock 0.4, Groovy 1.7.2, Java 1.6.0_22


Please provide any additional information below. You can also assign
labels.

ant 1.7.1, osx may be related? I think i tried a clean compile without ant too. 

Is p1 == second parameter the conflict and an implicit property? If so perhaps 
listing reserved names may help (there are others...), or better yet a clear 
compilation error message if that is possible.


```

Original issue reported on code.google.com by `peter.lu...@gmail.com` on 2 Dec 2010 at 7:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 2 Dec 2010 at 12:17
- Changed state: **Accepted**
- Added labels: **Milestone-0.5**

**Comment by GoogleCodeExporter** [comment]
```
Have you come across any other names that don't work (besides p0, p1, etc)?
```

Original comment by `pnied...@gmail.com` on 2 Dec 2010 at 2:35

**Comment by GoogleCodeExporter** [comment]
```
No; seams to be pn where n is index of parameters. Explicity naming the 
parameters (on the feature method) makes not difference. I also tried with 
groovy 1.7.5 and isolated to just groovyc:

$ ../groovy-1.7.5/bin/groovyc -e -cp lib/spock-core-0.4-groovy-1.7.jar 
src/HelloSpock.groovy 
null
>>> stacktrace:
java.lang.NullPointerException
    at org.objectweb.asm.MethodWriter.visitLocalVariable(Unknown Source)
    at org.objectweb.asm.MethodAdapter.visitLocalVariable(Unknown Source)
    at org.codehaus.groovy.classgen.CompileStack.clear(CompileStack.java:331)
    at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:621)
    at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:591)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:123)
    at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:686)
    at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1039)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:50)
    at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:276)
    at org.codehaus.groovy.control.CompilationUnit$11.call(CompilationUnit.java:738)
    at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:932)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:509)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:487)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:464)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:448)
    at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:57)
    at org.codehaus.groovy.tools.FileSystemCompiler.doCompilation(FileSystemCompiler.java:170)
    at org.codehaus.groovy.tools.FileSystemCompiler.commandLineCompile(FileSystemCompiler.java:138)
    at org.codehaus.groovy.tools.FileSystemCompiler.main(FileSystemCompiler.java:152)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:108)
    at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:130)

```

Original comment by `peter.lu...@gmail.com` on 2 Dec 2010 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
then i am note sure what will happen using 'iterationCount' etc (which is 
something that should be documented, specially for web func testing one wants 
to check "row" as $("table.stuff tr", row) without writing it)
```

Original comment by `peter.lu...@gmail.com` on 2 Dec 2010 at 10:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 4 Dec 2010 at 9:30
- Changed state: **Fixed**
