### ISSUE TITLE
Can't substitute values containing "$" in @Unroll 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#154]
```
The attached test fails with
java.lang.IndexOutOfBoundsException: No group 2
    at java.util.regex.Matcher.group(Matcher.java:470)
    at java.util.regex.Matcher.appendReplacement(Matcher.java:737)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

...presumably because #text contains text with "$1" or "$2" in them.

What version of Spock and Groovy are you using?
Spock 0.4; Groovy 1.7.5

Please provide any additional information below. You can also assign
labels.

```

Original issue reported on code.google.com by `jbrainsb...@gmail.com` on 7 Dec 2010 at 4:05

Attachments:
- [SellOneItemSpec.groovy](https://storage.googleapis.com/google-code-attachments/spock/issue-154/comment-0/SellOneItemSpec.groovy)

**Comment by GoogleCodeExporter** [comment]
```
This bug has already been fixed in 0.5-SNAPSHOT. 0.5 release is near.
```

Original comment by `pnied...@gmail.com` on 7 Dec 2010 at 9:41
- Changed state: **Duplicate**
- Added labels: **Milestone-0.5**
