### ISSUE TITLE
Unable to run tests inside Eclipse since upgrade to 0.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#162]
```
I now get the following in the console:

java.lang.NoSuchFieldError: optimizeRunOrder
    at org.spockframework.runtime.extension.builtin.OptimizeRunOrderExtension.visitSpec(OptimizeRunOrderExtension.java:33)
    at org.spockframework.runtime.ExtensionRunner.runGlobalExtensions(ExtensionRunner.java:44)
    at org.spockframework.runtime.ExtensionRunner.run(ExtensionRunner.java:38)
    at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:77)
    at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:54)
    at org.junit.runner.Runner.testCount(Runner.java:38)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(JUnit4TestClassReference.java:30)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunner.java:487)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:455)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

My launch configuration is a Junit 4 for all tests in my project.


```

Original issue reported on code.google.com by `hls...@gmail.com` on 22 Dec 2010 at 2:07

Attachments:
- [spock-run-conf.png](https://storage.googleapis.com/google-code-attachments/spock/issue-162/comment-0/spock-run-conf.png)

**Comment by GoogleCodeExporter** [comment]
```
My tests do run correctly from the command line (via Gradle).
```

Original comment by `hls...@gmail.com` on 22 Dec 2010 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
My mistake; "gradle eclipse" did a bad job of updating .classpath, leaving both 
0.4 and 0.5 (and deps) on the classpath. Resolved via "gradle cleanEclipse 
eclipse"
```

Original comment by `hls...@gmail.com` on 22 Dec 2010 at 2:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 22 Dec 2010 at 12:01
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 1 Jan 2011 at 1:22
- Added labels: **Milestone-0.6**
