### ISSUE TITLE
Exception when using data variable both as method parameter and in @Unroll naming pattern

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#201]
```
(similar to defect 200)

Using the following versions:
  groovy 'org.codehaus.groovy:groovy-all:1.8.1'
  testCompile 'org.spockframework:spock-core:0.6-groovy-1.8-SNAPSHOT'

1.  With this test case defined in src/test/groovy:

@Unroll({"strong typing breaks unroll '$v'"})
def "strong typing breaks unroll"(int v) {
    expect:
    v + 1 == v + 1

    where:
    [v] << [[1], [2], [3]]
}

2.  run "gradle test"

org.spockframework.runtime.extension.ExtensionException: Failed to instantiate 
@Unroll naming pattern
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:173)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:173)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:51)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:63)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:49)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:86)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.MethodInvocationUnmarshallingDispatch.dispatch(MethodInvocationUnmarshallingDispatch.java:48)
    at org.gradle.messaging.dispatch.DiscardOnFailureDispatch.dispatch(DiscardOnFailureDispatch.java:31)
    at org.gradle.messaging.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:129)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NoSuchMethodException: 
onair.exampletests.spock.HelloSpock$_$spock_feature_0_2_closure3.<init>(java.lan
g.Object, java.lang.Object)
    at java.lang.Class.getConstructor0(Class.java:2706)
    at java.lang.Class.getConstructor(Class.java:1657)
    ... 15 more
```

Original issue reported on code.google.com by `miehe.ri...@gmail.com` on 16 Sep 2011 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
Doesn't matter whether the method parameter is typed or not. Caused by 
http://jira.codehaus.org/browse/GROOVY-5040. Workaround implemented.
```

Original comment by `pnied...@gmail.com` on 4 Oct 2011 at 8:45
- Changed title: **Exception when using data variable both as method parameter and in @Unroll naming pattern**
- Changed state: **Fixed**
- Added labels: **Milestone-0.6**
