### ISSUE TITLE
Integration with Unitils is broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#390]
```
build.gradle

  testCompile group: 'org.spockframework', name: 'spock-core', version: '1.0-groovy-2.3-SNAPSHOT'
  testCompile group: 'org.spockframework', name: 'spock-spring', version: '1.0-groovy-2.3-SNAPSHOT'
  testCompile group: 'org.spockframework', name: 'spock-unitils', version: '0.7-groovy-2.0'
  testCompile group: 'org.unitils', name: 'unitils-core', version: '3.4.2'
  testCompile group: 'org.unitils', name: 'unitils-dbunit', version: '3.4.2'


Test class

  @UnitilsSupport
  @DataSet
  @ContextConfiguration("classpath:context.xml")
  class TestSpec extends Specification {

Stacktrace:

Caused by: java.lang.NoSuchMethodError: 
org.spockframework.runtime.model.SpecInfo.getSetupSpecMethod()Lorg/spockframewor
k/runtime/model/MethodInfo;
 at org.spockframework.unitils.UnitilsExtension.visitSpecAnnotation(UnitilsExtension.java:28)
 at org.spockframework.unitils.UnitilsExtension.visitSpecAnnotation(UnitilsExtension.java:23)
 at org.spockframework.runtime.ExtensionRunner.doRunAnnotationDrivenExtensions(ExtensionRunner.java:91)
 at org.spockframework.runtime.ExtensionRunner.runAnnotationDrivenExtensions(ExtensionRunner.java:62)
 at org.spockframework.runtime.ExtensionRunner.runAnnotationDrivenExtensions(ExtensionRunner.java:51)
 at org.spockframework.runtime.ExtensionRunner.run(ExtensionRunner.java:41)
 at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:88)
 at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:55)
 at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:43)
```

Original issue reported on code.google.com by `korma...@gmail.com` on 24 Feb 2015 at 1:08

**Comment by GoogleCodeExporter** [comment]
```
Issue is not actual. There is wrong version of spock-unitils module. Should be 
'1.0-groovy-2.3-SNAPSHOT' as core version.
```

Original comment by `korma...@gmail.com` on 25 Feb 2015 at 7:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 3 Mar 2015 at 2:46
- Changed state: **Invalid**
- Added labels: **Milestone-1.0**
