### ISSUE TITLE
Failed to load extension class 'IncludeExcludeExtension'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#66]
```
groovy-1.7.0
spock-0.4-groovy-1.7-snapshot (2010-01-27)

running a specification in eclipse galileo with groovy-eclipse plugin
throws an exception.

java.lang.ExceptionInInitializerError
    at
org.spockframework.runtime.SpecInfoBuilder.notifyGlobalExtensions(SpecInfoBuilde
r.java:226)
    at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:56)
    at org.spockframework.runtime.Sputnik.<init>(Sputnik.java:38)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at
org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:3
1)
    at
org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.jav
a:24)
    at
org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at
org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDef
aultPossibilitiesBuilder.java:29)
    at
org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestRefe
rence.java:29)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4Tes
tClassReference.java:25)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoa
der.java:40)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoad
er.java:30)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:452)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)
Caused by: org.spockframework.runtime.extension.ExtensionException: Failed
to load extension class
'org.spockframework.runtime.extension.builtin.IncludeExcludeExtension
org.spockframework.runtime.extension.builtin.RuleExtension'
    at
org.spockframework.runtime.extension.ExtensionRegistry.loadExtensionClass(Extens
ionRegistry.java:73)
    at
org.spockframework.runtime.extension.ExtensionRegistry.loadExtension(ExtensionRe
gistry.java:58)
    at
org.spockframework.runtime.extension.ExtensionRegistry.loadExtensions(ExtensionR
egistry.java:46)
    at
org.spockframework.runtime.extension.ExtensionRegistry.<init>(ExtensionRegistry.
java:41)
    at
org.spockframework.runtime.extension.ExtensionRegistry.<clinit>(ExtensionRegistr
y.java:34)
    ... 21 more
Caused by: java.lang.ClassNotFoundException:
org.spockframework.runtime.extension.builtin.IncludeExcludeExtension
org.spockframework.runtime.extension.builtin.RuleExtension
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at
org.spockframework.runtime.extension.ExtensionRegistry.loadExtensionClass(Extens
ionRegistry.java:71)
    ... 25 more


```

Original issue reported on code.google.com by `hasteb...@gmail.com` on 27 Jan 2010 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
org.spockframework.runtime.extension.builtin.IncludeExcludeExtension exists in 
the
sources jar, but not in the jar with the class files.

```

Original comment by `hasteb...@gmail.com` on 27 Jan 2010 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
IncludeExcludeExtension is included in the Jar. I think this is a newline 
problem when parsing the descriptor (the 
class name in the stack trace is 
'org.spockframework.runtime.extension.builtin.IncludeExcludeExtension 
org.spockframework.runtime.extension.builtin.RuleExtension'). What's your 
platform? Windows?
```

Original comment by `pnied...@gmail.com` on 27 Jan 2010 at 4:09

**Comment by GoogleCodeExporter** [comment]
```
The line numbers in your stack trace don't match the latest spock snapshot. I 
think you have multiple spock 
Jars on your class path. Could you add the following Groovy class to your code 
base (alongside your specs), 
run it, and post its output?

class DescriptorPrinter {
  static main(args) {
    def resources = DescriptorPrinter.classLoader.getResources("META-
INF/services/org.spockframework.runtime.extension.IGlobalExtension")
    resources.each {
      println it.text
      println()
    }
  }
}
```

Original comment by `pnied...@gmail.com` on 27 Jan 2010 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
My platform is Windows.

{{{
org.spockframework.runtime.extension.builtin.RuleExtension

org.spockframework.runtime.extension.builtin.IncludeExcludeExtension
org.spockframework.runtime.extension.builtin.RuleExtension


}}}
```

Original comment by `hasteb...@gmail.com` on 28 Jan 2010 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
The .classpath file for the Eclipse project:

{{{
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="con"
path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.
launcher.StandardVMType/JavaSE-1.6"/>
    <classpathentry exported="true" kind="con" path="GROOVY_SUPPORT"/>
    <classpathentry kind="lib" path="lib/junit-4.8.1.jar"/>
    <classpathentry kind="lib" path="lib/cglib-nodep-2.2.jar"/>
    <classpathentry kind="lib" path="lib/objenesis-1.2.jar"/>
    <classpathentry kind="lib"
path="/openjumplib-20091208/openjump-core-1.3-SNAPSHOT.jar"/>
    <classpathentry kind="lib" path="lib/spock-core-0.4-groovy-1.7-20100127.jar"/>
    <classpathentry kind="output" path="bin"/>
</classpath>
}}}
```

Original comment by `hasteb...@gmail.com` on 28 Jan 2010 at 8:00

**Comment by GoogleCodeExporter** [comment]
```
Output is another strong indication that you have two Spock Jars on the class 
path. Maybe one of them is in your 
JRE's lib/ext directory, or you have defined it as a user library in Eclipse.
```

Original comment by `pnied...@gmail.com` on 28 Jan 2010 at 10:44

**Comment by GoogleCodeExporter** [comment]
```
In DescriptorPrinter, change "println it.text" to "println it", and you should 
see where the Spock Jars are located.
```

Original comment by `pnied...@gmail.com` on 28 Jan 2010 at 11:32

**Comment by GoogleCodeExporter** [comment]
```
You're right. NOT A BUG.

```

Original comment by `hasteb...@gmail.com` on 28 Jan 2010 at 11:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 28 Jan 2010 at 12:27
- Changed state: **NotABug**
- Added labels: **Milestone-0.4**
