### ISSUE TITLE
NoSuchMethodError when running grails test-app with spock plugin 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#67]
```
I installed the spock plugin 0.4-SNAPSHOT into my grails 1.2.1 project,
without even implementing a singe spock test I am not able to run my old
tests by calling

grails test-app

I get the following exception

Error executing script TestApp: : java.lang.NoSuchMethodError:
org.spockframework.compiler.SpecParser.<init>(Lorg/spockframework/compiler/Error
Reporter;)V
gant.TargetExecutionException: : java.lang.NoSuchMethodError:
org.spockframework.compiler.SpecParser.<init>(Lorg/spockframework/compiler/Error
Reporter;)V
        at gant.Gant$_dispatch_closure4.doCall(Gant.groovy:331)
        at gant.Gant$_dispatch_closure6.doCall(Gant.groovy:334)
        at gant.Gant$_dispatch_closure6.doCall(Gant.groovy)
        at gant.Gant.withBuildListeners(Gant.groovy:344)
        at gant.Gant.this$2$withBuildListeners(Gant.groovy)
        at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
        at gant.Gant.dispatch(Gant.groovy:334)
        at gant.Gant.this$2$dispatch(Gant.groovy)
        at gant.Gant.invokeMethod(Gant.groovy)
        at gant.Gant.processTargets(Gant.groovy:495)
        at gant.Gant.processTargets(Gant.groovy:480)
Caused by: : java.lang.NoSuchMethodError:
org.spockframework.compiler.SpecParser.<init>(Lorg/spockframework/compiler/Error
Reporter;)V
        at
org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at
_GrailsCompile_groovy$_run_closure3_closure9.doCall(_GrailsCompile_groovy:103)
        at
_GrailsCompile_groovy$_run_closure3_closure9.doCall(_GrailsCompile_groovy)
        at
_GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:287)
        at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
        at _GrailsCompile_groovy$_run_closure3.doCall(_GrailsCompile_groovy:90)
        at _GrailsCompile_groovy$_run_closure2.doCall(_GrailsCompile_groovy:57)
        at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:109)
        at TestApp$_run_closure1.doCall(TestApp.groovy:102)
        at gant.Gant$_dispatch_closure4.doCall(Gant.groovy:324)
        ... 10 more
Caused by: java.lang.NoSuchMethodError:
org.spockframework.compiler.SpecParser.<init>(Lorg/spockframework/compiler/Error
Reporter;)V
        at
org.spockframework.compiler.SpockTransform.processSpec(SpockTransform.java:64)
        at
org.spockframework.compiler.SpockTransform.visit(SpockTransform.java:52)
        at
org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationV
isitor.java:303)
        at
org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.j
ava:820)
        at
org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.jav
a:513)
        at
org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUn
it.java:489)
        at
org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:466)
        at
org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:450)
        at
org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:57)
        at
org.codehaus.groovy.tools.FileSystemCompiler.doCompilation(FileSystemCompiler.ja
va:170)
        at org.codehaus.groovy.ant.Groovyc.compile(Groovyc.java:816)
        at org.codehaus.groovy.ant.Groovyc.execute(Groovyc.java:544)
        at
org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 20 more
Error executing script TestApp: : java.lang.NoSuchMethodError:
org.spockframework.compiler.SpecParser.<init>(Lorg/spockframework/compiler/Error
Reporter;)V
```

Original issue reported on code.google.com by `thomas.e...@gmail.com` on 8 Feb 2010 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
You are most likely running into http://jira.codehaus.org/browse/GRAILS-5624. 
Please try to clear your Ivy 
cache (~/.ivy2/cache) and let us know if this solves your problem.

```

Original comment by `pnied...@gmail.com` on 9 Feb 2010 at 10:15

**Comment by GoogleCodeExporter** [comment]
```
I am well aware of that issues, really got used to delete the dependencies to 
the
snapshots of my own projects I am building my grails projects on ...

seems that does not help anything, I got the following artifact from the 
repository
today:

#Generated by Maven
#Fri Feb 05 05:00:51 CET 2010
version=0.4-SNAPSHOT
groupId=org.spockframework
artifactId=spock-core

```

Original comment by `thomas.e...@gmail.com` on 9 Feb 2010 at 2:29

**Comment by GoogleCodeExporter** [comment]
```
Can you attach the spock-core Jar that was downloaded by Ivy?
```

Original comment by `pnied...@gmail.com` on 9 Feb 2010 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
I attached the file, I tried to do this on another machine yesterday and it 
worked
there, so I will have another look into this now 
```

Original comment by `thomas.e...@gmail.com` on 10 Feb 2010 at 8:34

Attachments:
- [spock-core-0.4-SNAPSHOT.jar](https://storage.googleapis.com/google-code-attachments/spock/issue-67/comment-4/spock-core-0.4-SNAPSHOT.jar)

**Comment by GoogleCodeExporter** [comment]
```
found the problem, there was a spock-core 0.3 version lying around on this 
machine,
after removing it everything works fine
```

Original comment by `thomas.e...@gmail.com` on 10 Feb 2010 at 9:17

**Comment by GoogleCodeExporter** [comment]
```
This seems to be a common pitfall, so I've added 
http://code.google.com/p/spock/issues/detail?id=68
```

Original comment by `pnied...@gmail.com` on 10 Feb 2010 at 12:52
- Changed state: **NotABug**
