### ISSUE TITLE
Fixup of feature method name in stack trace doesn't work for base specs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#75]
```
class BaseSpec extends Specification {
  def "foo"() {
    expect: false
  }
}

class DerivedSpec extends BaseSpec {
    def bar() {
        expect: false
    }
}

Output:

Condition not satisfied:

false

    at BaseSpec.$spock_feature_0_0(BaseSpec.groovy:8)


Condition not satisfied:

false

    at DerivedSpec.bar(DerivedSpec.groovy:23)
```

Original issue reported on code.google.com by `pnied...@gmail.com` on 2 Mar 2010 at 12:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 8 Mar 2010 at 9:48
- Changed state: **Fixed**
