### ISSUE TITLE
Error when running single method from base spec

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#76]
```
class BaseSpec extends Specification {
  def "foo"() {
    expect: false
  }
}

class DerivedSpec extends BaseSpec {
    def bar() {
        expect: false
    }
}

First run class DerivedSpec. Then select method "foo" from IDEA's JUnit view 
and run it. Result:

java.lang.Exception: No tests found matching Method foo(DerivedSpec) from 
org.junit.internal.requests.ClassRequest@583e97df
    at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:37)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:60)

Seems we don't search for methods in base spec when the filter is applied.

```

Original issue reported on code.google.com by `pnied...@gmail.com` on 2 Mar 2010 at 12:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 8 Mar 2010 at 10:38
- Changed state: **Fixed**
