### ISSUE TITLE
Eclipse and spock-core jar location

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#88]
```
I have a very simple project (run in Eclipse) with single Specification
(from one of the examples). I am using spock-core-0.4-20100108-0501.jar. 

When I have this jar in my project's lib directory everything is fine
(Project->lib->spock-core-0.4-20100108-0501.jar). However when I move this
jar outside of the project to another location I am being hit with
following exception:

org.spockframework.runtime.InvalidSpecException: Class 'FoobarSpec' is not
a Spock specification
    at
org.spockframework.runtime.SpecInfoBuilder.getSpecMetadata(SpecInfoBuilder.java:
92)
    at
org.spockframework.runtime.SpecInfoBuilder.buildSpec(SpecInfoBuilder.java:82)
    at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:51)
    at org.spockframework.runtime.Sputnik.<init>(Sputnik.java:38)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorI
mpl.java:39)
    at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorA
ccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at
org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:3
1)
    at
org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.jav
a:24)
    at
org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at
org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDef
aultPossibilitiesBuilder.java:29)
    at
org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestRefe
rence.java:29)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4Tes
tClassReference.java:25)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoa
der.java:40)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoad
er.java:30)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:452)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)

I does not matter whether this jar (spock-core) lands in another location
that is open in Eclipse as project (and then linked with "Add jar" option)
or is in other external location (and then linked with "Add external jar"
option). In both cases the outcome is the same - above exception.

```

Original issue reported on code.google.com by `pdol...@gmail.com` on 2 Apr 2010 at 10:02

**Comment by GoogleCodeExporter** [comment]
```
I've created a new Groovy project, added JUnit and spock-core as external Jars, 
but couldn't reproduce your 
problem. The exception you are getting means that the Spock compiler plugin 
("AST transform") wasn't run 
during Groovy compilation. I recommend to:
 - Read the "important notes" in the Eclipse section of http://code.google.com/p/spock/wiki/GettingStarted
 - Use the latest snapshot of the Groovy Eclipse plugin
 - Use the latest snapshot of  spock-core
 - Clean the project before you run the spec

If the problem persists, it is most likely a bug in the Groovy Eclipse plugin, 
and I recommend to raise an issue 
there. It would help if you attached a zip of your project containing 
everything to reproduce your problem.
```

Original comment by `pnied...@gmail.com` on 3 Apr 2010 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
Sorry for the late answer. I attached two projects: one of them contains one
Specification class and the other contains jars. Additionally Test project (the 
one
with spec class) contains the same jar as in TestLib project.

When I run spec class as a Junit test with Spock jar linked from the TestLib 
project
I got the exception as pasted in my first comment. This is how the projects in
attachment are configured right now. If you manage to get mentioned exception, 
try to
link the spock jar that is in Test project (and of course exclude the one from
TestLib project) - you should have no exception and specification successfully 
run.

I am using the newest development build of Groovy plug-in (2.0.2.20100403-2, 
because
of your suggestion) - previously I was using the most recent official release 
(it was
2.0.1 I guess). My Eclipse version is 3.5.2.
```

Original comment by `pdol...@gmail.com` on 5 Apr 2010 at 5:19

Attachments:
- [projects.zip](https://storage.googleapis.com/google-code-attachments/spock/issue-88/comment-2/projects.zip)

**Comment by GoogleCodeExporter** [comment]
```
For Groovy 1.7-based projects you need to use spock-core-groovy-1.7, which is 
available from here: 
http://m2repo.spockframework.org/snapshots/org/spockframework/spock-core/0.4-gro
ovy-1.7-SNAPSHOT/
However, this isn't the cause for this problem. I can reproduce your problem 
when adding spock-core as a 
Project dependency, but I can't reproduce it when adding spock-core as an 
external dependency. (I'd be 
surprised if the latter didn't work because most Spock users I know use Maven 
and therefore external 
dependencies.) I've raised a Groovy-Eclipse issue here: 
http://jira.codehaus.org/browse/GRECLIPSE-703
```

Original comment by `pnied...@gmail.com` on 5 Apr 2010 at 6:08
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Yes, I was wrong in my first post - adding jar as EXTERNAL dependency does not 
make
exception to be thrown. I am glad you managed to reproduce the defect though. 
And
thanks for forwarding this issue to Groovy Eclipse plug-in team.
```

Original comment by `pdol...@gmail.com` on 5 Apr 2010 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this issue because it was found to be a Groovy Eclipse bug.
```

Original comment by `pnied...@gmail.com` on 21 Apr 2010 at 9:29
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this issue because it was found to be a Groovy Eclipse bug.
```

Original comment by `pnied...@gmail.com` on 21 Apr 2010 at 9:31
