### ISSUE TITLE
Spock trunk as at 2010-05-29 09:00+01:00 fails to install out of the box using Maven

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#93]
```
I need a version of Spock build for Groovy Trunk.  There doesn't seem to be one 
in teh 
downloads section so I tried checking out Spock Trunk to see if I could build 
it and install it.  I 
flipped a coin and used Maven rather than Gradle for the build and ran "mv 
clean install".  After 
downloading 3/4 of the known Maven universe :-( I eventually got the output 
below.

I am running Ubuntu Lucid with OpenJDK.

[ . . . many, many lines of stuff elided . . . ]
[INFO] Using Grails 1.2.2
Running pre-compiled script
Setting non-interactive mode
    [mkdir] Created dir: /home/Checkouts/Subversion/Spock_Trunk/target/test-reports/html
    [mkdir] Created dir: /home/Checkouts/Subversion/Spock_Trunk/target/test-reports/plain

Starting functional test phase ...
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Unable to start Grails

Embedded error: java.lang.reflect.InvocationTargetException
PermGen space
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 minutes 21 seconds
[INFO] Finished at: Sat May 29 09:15:57 BST 2010
[INFO] Final Memory: 249M/853M
[INFO] ------------------------------------------------------------------------
Application context shutting down...
Application context shutdown.

```

Original issue reported on code.google.com by `russel.winder` on 29 May 2010 at 8:27

**Comment by GoogleCodeExporter** [comment]
```
On a second run, so without all the Maven downloading, the error report is 
different:

[ . . . ]
[INFO] [site:attach-descriptor {execution: default-attach-descriptor}]
[INFO] [grails:exec {execution: package-plugin}]
[INFO] Using Grails 1.2.2
Running pre-compiled script
    [mkdir] Created dir: /home/Checkouts/Subversion/Spock_Trunk/spock-grails/target/plugin-info
     [copy] Copying 1 file to /home/Checkouts/Subversion/Spock_Trunk/spock-grails/target/plugin-info
   [delete] Deleting: /home/Checkouts/Subversion/Spock_Trunk/spock-grails/grails-spock-0.5-groovy-1.6-
SNAPSHOT.zip
      [zip] Building zip: /home/Checkouts/Subversion/Spock_Trunk/spock-grails/grails-spock-0.5-groovy-1.6-
SNAPSHOT.zip
[INFO] [grails:maven-functional-test {execution: build}]
[INFO] Using Grails 1.2.2
Running pre-compiled script
Setting non-interactive mode
    [mkdir] Created dir: /home/Checkouts/Subversion/Spock_Trunk/target/test-reports/html
    [mkdir] Created dir: /home/Checkouts/Subversion/Spock_Trunk/target/test-reports/plain

Starting functional test phase ...
Running Grails application..
java.lang.OutOfMemoryError: PermGen space
    at org.apache.log4j.Category.forcedLog(Category.java:388)
    at org.apache.log4j.Category.log(Category.java:853)
    at org.apache.juli.logging.impl.Log4JLogger.error(Log4JLogger.java:257)
    at org.grails.tomcat.TomcatServer.start(TomcatServer.groovy:135)
    at grails.web.container.EmbeddableServer$start.call(Unknown Source)
    at _GrailsRun$_run_closure5_closure12.doCall(_GrailsRun.groovy:158)
Server failed to start: java.lang.OutOfMemoryError: PermGen space
Application context shutting down...
Application context shutdown.

```

Original comment by `russel.winder` on 29 May 2010 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
@Luke: Can we make Grails fork a new JVM (with increased permgen space) for 
running functional tests? This 
way, people building spock wouldn't have to increase permgen space by 
themselves.

@Russel: For now you can either just build what you need (I assume you don't 
need spock-grails), or increase 
permgen space via MAVEN_OPTS:

export MAVEN_OPTS='-XX:MaxPermSize=250m' 

I have this in my init script.

```

Original comment by `pnied...@gmail.com` on 29 May 2010 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
Building and installing just spock-core works for me.
```

Original comment by `russel.winder` on 30 May 2010 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this issue since it's a Grails permgen issue which can be resolved 
by giving it more permgen (as explained earlier).
```

Original comment by `pnied...@gmail.com` on 23 Jun 2010 at 9:53
- Changed state: **WontFix**
