### ISSUE TITLE
Adding member variable to specification class causes test failure with ugly exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sampig/spock#97]
```
Hello

I am using spock 0.4 (stable) for groovy 1.7.

I have very strange issue here: whenever I add a member variable to
specification class like this:

class UserDaoSpec extends TransactionalSpecification {

    def user1
    def user2

       .....
}

I end up with SecurityException as pasted below.

Stack trace:

java.lang.SecurityException: class "org.junit.Rule"'s signer information
does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:807)
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:488)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:626)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at
org.spockframework.runtime.extension.builtin.RuleExtension.visitSpec(RuleExtensi
on.java:29)
    at
org.spockframework.runtime.SpecInfoBuilder.runGlobalExtensions(SpecInfoBuilder.j
ava:228)
    at
org.spockframework.runtime.SpecInfoBuilder.runExtensions(SpecInfoBuilder.java:71
)
    at
org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:76)
    at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:53)
    at org.junit.runner.Runner.testCount(Runner.java:38)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(J
Unit4TestClassReference.java:30)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunn
er.java:487)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:455)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)
```

Original issue reported on code.google.com by `pdol...@gmail.com` on 30 May 2010 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Oh and forget to add -> Besides small defects (like this one) Spock is really 
awesome
library !

Thanks for doing it, guys !
```

Original comment by `pdol...@gmail.com` on 30 May 2010 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
To be clear about code snippet:

class UserDaoSpec extends TransactionalSpecification {

    def user1
    def user2

       .....
}


TransactionalSpecification is my base class which wraps each test case in
transaction. TransactionalSpecification extends Specification class of course.
```

Original comment by `pdol...@gmail.com` on 30 May 2010 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Do you have JUnit on your project classpath? Maybe even multiple versions?
```

Original comment by `pnied...@gmail.com` on 30 May 2010 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
Yes, I do: junit-4.8.1.
```

Original comment by `pdol...@gmail.com` on 30 May 2010 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
Which Eclipse version do you use? There are several similar bug reports in 
Eclipse's issue tracker.
```

Original comment by `pnied...@gmail.com` on 30 May 2010 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Version: 3.5.2.R35
```

Original comment by `pdol...@gmail.com` on 30 May 2010 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
I think the problem is that for some reason, you have multiple versions of 
JUnit on your test runtime classpath. 
Google tells me that the following often helps. Could you try this?

1. Project/Build Path/Configure Build Path
2. Order and Export tab
3. Move JUnit4 on top.
```

Original comment by `pnied...@gmail.com` on 30 May 2010 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
It seems you were right - that's an Eclipse problem.

I copied following files from my other Eclipse project and it works:
.classpath
.project
.settings/org.eclipse.jdt.core.prefs
.settings/org.eclipse.wst.common.component
.settings/org.eclipse.wst.common.project.facet.core.xml

I don't know which one exactly was wrong but I will dig for it in the spare 
time.

Thanks for the clue!
```

Original comment by `pdol...@gmail.com` on 30 May 2010 at 9:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `pnied...@gmail.com` on 30 May 2010 at 10:13
- Changed state: **WontFix**
